# 虚假唤醒

这个虚假唤醒是个啥呢？

首先我们先看看这个代码（让A,B交替输出）

```java
public class 虚假唤醒 {
    public static void main(String[] args) {
        T t = new T();
        new Thread(()->{while (true) t.A();}).start();
        new Thread(()->{while (true) t.B();}).start();
    }
}

class T{
    private int num = 1;
    public synchronized void A(){
        if (num != 1){
            try {
                wait();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("A");
        num = 2;
        notifyAll();
    }

    public synchronized void B(){
        if (num != 2){
            try {
                wait();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("B");
        num = 1;
        notifyAll();
    }
}
```

来看看执行效果（算了，节省篇幅，就不放图了），执行结果确实没问题。

现在我们把`虚假唤醒`的线程多加两个。

```java
public class 虚假唤醒 {
    public static void main(String[] args) {
        T t = new T();
        new Thread(()->{while (true) t.A();},"A1").start();
        new Thread(()->{while (true) t.B();},"B1").start();
        //新增
        new Thread(()->{while (true) t.A();},"A2").start();
        new Thread(()->{while (true) t.B();},"B2").start();
    }
}
```

![](https://pic.imgdb.cn/item/60214c7b3ffa7d37b3c0f8f8.png)

出现了!!!

这是为什么呢？

1. 假设B1率先获得了时间片，因为此时num等于1，因此B1被阻塞。
2. A1获得了时间片，顺利执行，num = 2了，输出A。
3. 接着B2获得时间片，顺利执行，输出B。
4. 重头戏来了，B1再次获得时间片，他是从上次被阻塞的地方开始执行的，不需要去进行if判断了，因此还会输出B。

虚假唤醒的意思就是，在第3步时，B2本来是想唤醒A1或者A2的，结果出问题了，B1拿上了时间片。

**解决办法**

**在if块中使用wait方法，是非常危险的，因为一旦线程被唤醒，并得到锁，就不会再判断if条件，而执行if语句块外的代码，所以建议，凡是先要做条件判断，再wait的地方，都使用while循环来做。** 

```java
class T{
    private int num = 1;
    public synchronized void A(){
        while (num != 1){
            try {
                wait();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("A");
        num = 2;
        notifyAll();
    }

    public synchronized void B(){
        while (num != 2){
            try {
                wait();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("B");
        num = 1;
        notifyAll();
    }
}
```

好了这次就绝对不会出问题了。

因为if只会执行一次，而while只有条件为true时才会放行。

注:由于条件苛刻（必须按照严格的顺序才能产生虚假唤醒现象），因此请各位小伙伴多找找（比较少见），但是不能因为少见就不去处理，否则在真实开发中可能会导致很严重的后果。